export const TIPUS_INSTANCIES = `TIPUS D’INSTÀNCIES:
1- INSTÀNCIA GENÈRICA.
2- INSTÀNCIA BECA MENJADOR.
3- INSTÀNCIA DUPLICAT DE CERTIFICAT.`;

export const LLISTA_INSTANCIES = [
    "INSTÀNCIA GENÈRICA",
    "INSTÀNCIA BECA MENJADOR",
    "INSTÀNCIA DUPLICAT DE CERTIFICAT"
]